services:
  web:
    container_name: appbase64
    restart: always
    build: .
    ports:
      - "3501:3000"
    links:
      - mongo
    volumes:
      - .:/home/node/app
    environment: 
      BD_CNN: mongodb://mongo/files
      PORT: 3000