services:
  web:
    container_name: planb
    restart: always
    image: sisedgar/planb
    ports:
      - "3501:3501"
    links:
      - mongo
    environment: 
      BD_CNN: mongodb://mongo/files
      PORT: 3501
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo-vol:/data/db